### ISSUE TITLE
Consistent Operator VM Setup

### ISSUE THREAD

**Issue by aubreynigoza** [CSUN-SeniorDesign/sandbox-worms-infrastructure#21]
Let's decide on what flavor of Linux to use as our main client computer (installed on our laptop).

**Comment by nky9514** [comment]
Since both you and John will be using CentOS, let's go with that. I just confirmed that John is using CentOS 7 which I'll be downloading and installing here in just a bit.

**Comment by aubreynigoza** [comment]
WHen you guys have the VM ready, can i copy it so i dont need to configure one for me? :)

**Comment by jpvinuya** [comment]
@aubreynigoza do you want the .vmdk file?
