### ISSUE TITLE
Project 2 CircleCI Workflow System Setup

### ISSUE THREAD

**Issue by Mark-Quark** [CSUN-SeniorDesign/sandbox-worms-infrastructure#59]

**Comment by aubreynigoza** [comment]
Workflow has been setup. With our current simple blog, the workflow doesn't makes that much sense. However, if our blog or applications, would run multiple tests, then the workflow will makes more sense.

I have it set to build -> test -> deploy 
There are
staging deploy
master deploy (requires hold -> approval)
